/galaxy_camera_node:
  ros__parameters:
    camera_name: narrow_stereo
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    frame_id: "camera_optical_frame"
    use_sensor_data_qos: true
    exposure_time: 4000
    gain: 8
    fps: 100

/armor_detector:
  ros__parameters:
    debug: false
    # detect_color: 1
    binary_thres: 100

    classifier_threshold: 0.7
    ignore_classes: ["negative"]
    

/armor_processor:
  ros__parameters:
    target_frame: world
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 1e-3
      sigma2_q_yaw: 1e1
      sigma2_q_r: 80.0

      r_xyz_factor: 4e-4
      r_yaw: 1e-2

    tracker:
      max_match_distance: 0.6
      max_match_yaw_diff: 0.85
      tracking_thres: 5
      lost_time_thres: 1.0
      

# Q值为过程噪声,越小系统越容易收敛，
# 我们对模型预测的值信任度越高；但是太小则容易发散，
# 如果Q为零,那么我们只相信预测值;Q值越大我们对于预测的信任度就越低,而对测量值的信任度就变高,
# 如果Q值无穷大,那么我们只信任测量值;
# R值为测量噪声,太小太大都不一定合适。R
# 太大，卡尔曼滤波响应会变慢，因为它对新测量的值的信任度降低；
# # 越小系统收敛越快，但过小则容易出现震荡；
# 测试时可以先将Q从小往大调整，将R从大往小调整；先固定一个值去调整另外一个值，看收敛速度与波形输出。